# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('palavra', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Requisi\xe7\xe3o',
                'verbose_name_plural': 'Requisi\xe7\xf5es',
            },
        ),
    ]
