# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='arquivo',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
